### ISSUE TITLE
[Bug]: color focus on input not working properly when hovering the input

### ISSUE THREAD

**Issue by driss-chelouati** [shuriken-ui/nuxt#107]

**Comment by JohnCampionJr** [comment]
@driss-chelouati Encountered this too, been over a month, can we get a fix please?

**Comment by driss-chelouati** [comment]
Yes, its in my planning for the end of the week. Going to make a few updates to the tailwind and nuxt packages.

**Comment by stafyniaksacha** [comment]
This has been fixed https://tairo.cssninja.io/documentation/reference/forms/input#focus
