### ISSUE TITLE
[BUG] BaseAutocomplete: classes not correctly applied when allowCreate is true

### ISSUE THREAD

**Issue by zaosoula** [shuriken-ui/nuxt#114]
When allowCreate is `true`, and there are no filtered results the dropdown doesn't have the correct styling.
When allowCreate is `true`, and there are some results, the create {{query}} item doesn't match the other item's style.

![Screenshot 2024-02-28 at 19 42 55](https://github.com/shuriken-ui/nuxt/assets/1884246/5a20e644-dd17-4508-a995-9a387cf0ca60)
![Screenshot 2024-02-28 at 19 43 12](https://github.com/shuriken-ui/nuxt/assets/1884246/e4c28f74-4860-40dc-a384-ef4b65d73c8a)

**Comment by stafyniaksacha** [comment]
This is fixed in latest release!
