### ISSUE TITLE
Option to change dash border

### ISSUE THREAD

**Issue by larrasu** [shuriken-ui/nuxt#12]
Is there a way to change the border of inputs on focus?

![image](https://github.com/shuriken-ui/nuxt/assets/74983120/12b91b8b-c8f5-4be9-9f7b-ae3304a52ebc)

**Comment by stafyniaksacha** [comment]
Hello!

You may need to create a css rule to override the default behavior, as it's actually defined in a [taiwlind plugin](https://github.com/shuriken-ui/tailwind/blob/46b895c9fca3490a13014d6df08256dffd7d89d5/src/plugins/components.ts#LL32C7-L44C9). We will create settings on the next update, so it's easier to customize. Can you tell us what are you trying to achieve? 

Here are the default value:
```postcss
.nui-focus {
  @apply outline-1 outline-dashed outline-offset-2;
  @apply outline-transparent;

  &:focus-within {
    @apply outline-muted-300 dark:outline-muted-600;
    @apply outline-dashed ring-0;
  }

  &:focus-visible {
    @apply outline-2;
  }
}
```

**Comment by hyp530** [comment]
> 

I tried to remove the dotted line as well. Good to know that you will create settings.

**Comment by stafyniaksacha** [comment]
This is now possible in https://github.com/shuriken-ui/nuxt/releases/tag/v1.0.0

```ts
// tailwind.config.ts
export default withShurikenUI({
  theme: {
    extend: {
      shurikenUi: {
        focus: {
          width: '0',
        }
      },
    },
  },
})
```

> See available values here: https://github.com/shuriken-ui/tailwind/blob/0458cdb4739b9a16359e4f9269beeee79019fb26/src/plugins/components/focus.ts#L6-L10
