### ISSUE TITLE
fix(BaseDropdown): add portal props to render the downdown in the body instead of the natural parent element

### ISSUE THREAD

**Issue by zaosoula** [shuriken-ui/nuxt#125]
Sometimes i need to pass the portal props to the Float component to render the dropdown out of the natural parent element 

In this case the table need an overflow-hidden to work property (TairoTable) and the dropdown get cropped due to it being renderer inside the table, using the portal props on the Float component would allow to fix this issue

![Screenshot 2024-07-08 at 09 34 25](https://github.com/shuriken-ui/nuxt/assets/1884246/0171e6cc-1f4d-495a-aaf6-f8d8cb8668bb)

**Comment by stafyniaksacha** [comment]
Hello @zaosoula

You can use the `fixed` prop on most components: https://github.com/shuriken-ui/nuxt/blob/main/components/base/BaseDropdown.vue#L17-L20

`<BaseDropdown fixed>`

**Comment by zaosoula** [comment]
Hi @stafyniaksacha, 

Unfortunatly the fixed props breaks the positioning. The dropdown get rendered outside screen boundaries
![Screenshot 2024-07-08 at 16 42 28](https://github.com/shuriken-ui/nuxt/assets/1884246/700e0c93-7d4e-4d48-8ee1-3d538dd33353)

**Comment by zaosoula** [comment]
@stafyniaksacha As you added the bug label, are you willing to let me do a PR to add the portal prop as an optional props of the BaseDropdown component ?

**Comment by stafyniaksacha** [comment]
Hello @zaosoula,
The plan is to expose all missing props of [`<Float>`](https://headlessui-float.vercel.app/vue/floatingui-options.html) in all components where it's used. (this components inject the portal, but we need to be able to configure it)

**Comment by zaosoula** [comment]
> Hello @zaosoula,
> 
> The plan is to expose all missing props of [`<Float>`](https://headlessui-float.vercel.app/vue/floatingui-options.html) in all components where it's used. (this component inject the portal, but we need to be able to configure it)

Ok i will give it a look. I might made a PR per component

**Comment by zaosoula** [comment]
poke: @stafyniaksacha
