### ISSUE TITLE
where is doc?

### ISSUE THREAD

**Issue by MOAB7698** [shuriken-ui/nuxt#15]
hi this look like so interesting but i cannot find example and a good docomation for learn how to use

**Comment by stafyniaksacha** [comment]
Hello @MOAB7698 

No dedicated documentation is available, it will be created soon!

For now, you can check https://tairo.cssninja.io/documentation/setup/nuxt-and-layers#how-tairo-uses-nuxt-layers and check components starting with `Base` prefix on https://tairo.cssninja.io/documentation/reference
