### ISSUE TITLE
install: `defineNuxtConfig` is not defined 

### ISSUE THREAD

**Issue by prescience-data** [shuriken-ui/nuxt#2]
## Issue

When attempting to install and activate using nuxt config I receive the following error:

```
Error while requiring module @shuriken-ui/nuxt: ReferenceError: defineNuxtConfig is not defined 

at node_modules/.pnpm/@shuriken-ui+nuxt@0.0.2_ac7fus7hmxy46xiwuygouu3dj4/node_modules/@shuriken-ui/nuxt/nuxt.config.ts:8:16

```

## Config

```js
export default defineNuxtConfig({
  modules: ["@shuriken-ui/nuxt"],
  nui: {
    defaultShapes: {
      accordion: "rounded",
      autocompleteItem: "rounded",
      avatar: "full",
      button: "rounded",
      buttonAction: "rounded",
      buttonIcon: "rounded",
      card: "rounded",
      dropdown: "rounded",
      iconBox: "rounded",
      input: "rounded",
      message: "curved",
      pagination: "rounded",
      progess: "full",
      prose: "rounded",
      tabSlider: "rounded",
      tag: "rounded"
    }
  }
})

```

## Environment

- Version: `^0.0.2`
- Ubuntu 22.04
- PNPM

**Comment by stafyniaksacha** [comment]
`@shuriken-ui/nuxt` is not a module, but a [layer](https://nuxt.com/docs/getting-started/layers)

You should have a `nuxt.config.ts` with `extends` key

```ts
export default defineNuxtConfig({
  extends: ["@shuriken-ui/nuxt"],
})
```

By contrast, the `nui` is for [app configuration](https://nuxt.com/docs/getting-started/configuration#app-configuration) and should be placed in `app.config.ts`

**Comment by prescience-data** [comment]
Ok great that works now.  🍾

However, there seems to be some sort of bug in the NuxtConfig type resolver as I get the following error, despite the `extends: string | string[]` property definitely being defined on `NuxtConfig` within the Nuxt types.  🤔

```
TS2345: Argument of type '{ extends: string; modules: string[]; strapi: { url: string; prefix: string; version: "v4"; cookie: {}; cookieName: string; }; }' is not assignable to parameter of type 'NuxtConfig'.   Object literal may only specify known properties, and 'extends' does not exist in type 'NuxtConfig'.
```


![image](https://user-images.githubusercontent.com/65471523/232182800-6462e885-cd07-4c61-9077-6e00ea2037fd.png)

(`ConfigSchema` internal interface)
![image](https://user-images.githubusercontent.com/65471523/232182861-9c539d88-5a12-4009-a1b2-31d7678d3b83.png)
