### ISSUE TITLE
Warn errors from `BaseInputFileHeadless` in `tairo`

### ISSUE THREAD

**Issue by prescience-data** [shuriken-ui/nuxt#22]
https://github.com/shuriken-ui/nuxt/blob/83f8835d5fb578bcad6cdbf74a00ef7343d89250/components/form/BaseInputFileHeadless.vue#L130

When attempting to use this component indirectly within [form-6.vue](https://github.com/cssninjaStudio/tairo/blob/989296835d98c5c2d6e939d164fe9faf98f8b5eb/.demo/pages/layouts/form-6.vue#L593) demo page, I receive the errors which appear to be caused by mismatches in the ref names:

```
 [Vue warn]: Property "el" was accessed during render but is not defined on instance. 
 [Vue warn]: Property "files" was accessed during render but is not defined on instance. 
 [Vue warn]: Property "preview" was accessed during render but is not defined on instance.
```

It triggers only on the refs that have been renamed immediately prior to export within `setup`.

**Comment by stafyniaksacha** [comment]
Should be fixed in https://github.com/shuriken-ui/nuxt/releases/tag/v1.0.0
