### ISSUE TITLE
tooltip position bottom not working

### ISSUE THREAD

**Issue by sagardspeed2** [shuriken-ui/nuxt#26]
In button, `data-tooltip-position="bottom"` means bottom position for tooltip is not working. however we can set top, left and right.

Step to reproduce
```
<button
type="button"
class="border-muted-200 hover:ring-muted-200 dark:hover:ring-muted-700 dark:border-muted-700 dark:bg-muted-800 dark:ring-offset-muted-900 flex h-9 w-9 items-center justify-center rounded-full border bg-white ring-1 ring-transparent transition-all duration-300 hover:ring-offset-4"
data-tooltip="Back to bots"
data-tooltip-position="bottom"
>
<Icon name="ph:arrow-bend-up-left" class="text-muted-400 h-5 w-5" />
</button>
```

Expected output,

when we set `data-tooltip-position="bottom"`,
the tooltip need to show below the targeted element

**Comment by stafyniaksacha** [comment]
Hello @sagardspeed2,

You can use `data-tooltip-position="down"` !
