### ISSUE TITLE
install: type error when using extends

### ISSUE THREAD

**Issue by prescience-data** [shuriken-ui/nuxt#6]
When activating the `extends` key on `defineNuxtConfig` I get the following type error:

### Error TS2345
> TS2345: Argument of type '{ extends: string[]; modules: string[]; app: { head: { htmlAttrs: { lang: string; }; }; }; content: {}; vite { plugins: Plugin_2[]; }; }' is not assignable to parameter of type 'NuxtConfig'.   Object literal may only specify known properties, and 'extends' does not exist in type 'NuxtConfig'.

### Sample config
```typescript
export default defineNuxtConfig({
  extends: ["@shuriken-ui/nuxt"],
  modules: [
    "@nuxtjs/tailwindcss",
    "@pinia/nuxt",
    "@nuxt/content",
    "@nuxtjs/supabase"
  ],
  app: {
    head: {
      htmlAttrs: {
        lang: "en"
      }
    }
  },
  content: {},
  vite: {
    plugins: [
      ViteSvgLoader({
        svgo: false
      })
    ]
  }
})

```

![image](https://user-images.githubusercontent.com/65471523/232962799-7e4c2188-875e-45e7-906f-fff872b2b871.png)

**Comment by stafyniaksacha** [comment]
Hello @prescience-data 

Did you run nuxt? Types will be generated on first run in `.nuxt` folder (or using `npx nuxt prepare`, often run on postinstall/prepare npm lifecycle)

Here is a simple reproduction:
https://stackblitz.com/edit/nuxt-starter-brl3sh?file=nuxt.config.ts,app.vue

Note that you do not need to include `@nuxtjs/tailwindcss` in your modules as it already injected by shuriken-ui!
