### ISSUE TITLE
bug: dropdown open list z-index is lower than autocomplete's

### ISSUE THREAD

**Issue by JohnCampionJr** [shuriken-ui/nuxt#79]
this causes the autocomplete's clear icon to show through a drop down's open list if a dropdown is placed above an autocomplete.

![image](https://github.com/shuriken-ui/nuxt/assets/1094820/0b4054e1-b86b-4b1c-a461-438f5aa1436f)

![image](https://github.com/shuriken-ui/nuxt/assets/1094820/b372449a-4442-4483-a331-802cf35197d4)

```
.nui-listbox .nui-listbox-options { z-index: 10 }
```

```
.nui-autocomplete .nui-autocomplete-results { z-index: 20 }
```

These should be the same :)

**Comment by stafyniaksacha** [comment]
Should be fixed in https://github.com/shuriken-ui/nuxt/releases/tag/v1.0.0
