### ISSUE TITLE
Change language or override default strings

### ISSUE THREAD

**Issue by OndraRehounek** [shuriken-ui/nuxt#91]
Hi, is there any way to change (or translate) default string values - like "empty" or "No results found."?

I bought Tairo template but without possibility of translation I would have to replace all the Shuriken components :/

**Comment by stafyniaksacha** [comment]
Hello @OndraRehounek 

Normally, all components string can be set using properties, ex with `BaseAutocomplete`: https://github.com/shuriken-ui/nuxt/blob/main/components/form/BaseAutocomplete.vue#L43-L49

If you see any string that can not be set, please advise us as it's a bug!

**Comment by OndraRehounek** [comment]
hello @stafyniaksacha,

thank you very much! I am sorry I didn't found that! it's working perfectly
